<a href="https://colab.research.google.com/github/basangoudapatil/DW-19-assignment/blob/main/Copy_of_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
import numpy as np
x=np.version.version
y=np.show_config()
print(x)
print(y)

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
import numpy as np
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
import numpy as np
a=np.array([10,20,30,40])
print(a.size)
print(a.itemsize)
print(a.size*a.itemsize)

4
8
32


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
import numpy as np
a=np.info(np.add)
print(a)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
import numpy as np
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
import numpy as np
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
import numpy as np
a=np.arange(10,50)
array=a
z=array[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
import numpy as np
a=np.arange(0,9)
print(a.reshape((3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
import numpy as np
a=[1,2,0,0,4,0]
z=np.array(a)
x=np.nonzero(z)
print(x)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
import numpy as np
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
import numpy as np
a=np.random.rand(3,3,3)
print(a)

[[[0.6264736  0.52852886 0.76173489]
  [0.96132915 0.16290124 0.03136547]
  [0.68042116 0.78139631 0.13792994]]

 [[0.90321325 0.11209255 0.39203993]
  [0.95322209 0.51189244 0.55463292]
  [0.05792704 0.41760901 0.45435169]]

 [[0.99256098 0.64723502 0.77017158]
  [0.28050681 0.97290255 0.42161821]
  [0.76207937 0.08562783 0.26455878]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
import numpy as np
a=np.random.rand(10,10)
print(a, '\n')
z=np.max(a), '\n'
print(z, '\n')
x=np.min(a), '\n'
print(x, '\n')

[[3.37304991e-01 5.66718029e-01 9.49589276e-01 1.00762634e-01
  1.48517508e-01 6.38814836e-02 2.23850268e-01 3.69017977e-02
  6.85397480e-01 1.23969172e-01]
 [8.27798993e-01 4.05678216e-01 1.07115756e-01 6.53043970e-01
  7.42592874e-01 5.54700486e-01 6.29835449e-01 1.61835996e-01
  6.73129907e-01 5.56568755e-02]
 [5.02339786e-01 7.92481182e-01 7.22826305e-01 1.73118440e-01
  4.85012583e-01 3.89937304e-01 2.99126967e-01 9.30356184e-01
  4.96987433e-01 8.91615818e-01]
 [4.07756546e-01 6.58300386e-01 6.17402094e-01 6.77256446e-01
  8.05389325e-01 7.30614372e-01 8.15329441e-02 7.56407230e-01
  5.15700425e-01 4.15136820e-01]
 [7.77453623e-01 9.49869995e-01 6.88961799e-01 5.39636451e-01
  4.54028704e-01 1.54678396e-01 8.69827189e-01 4.60689962e-01
  6.85009663e-01 6.38681298e-01]
 [4.66391800e-01 6.15033464e-01 9.11893929e-01 3.69753572e-01
  8.56015765e-01 7.09949466e-01 1.56318811e-01 6.47492716e-01
  2.99035014e-01 7.22131489e-01]
 [4.40812847e-01 4.28763935e-01 3.98849904e-01 9.82308802e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
import numpy as np
a=np.random.random(30)
print(a, '\n')
z=np.median(a)
print(z)

[0.91808312 0.12085266 0.41225187 0.00494473 0.39060298 0.47530915
 0.12897432 0.52335356 0.78623692 0.36716644 0.32110128 0.3674841
 0.65196272 0.17609764 0.2313264  0.41658396 0.52141    0.50659389
 0.50443409 0.60880164 0.97731981 0.04214504 0.20943506 0.71807842
 0.68997103 0.22735416 0.68588808 0.80163174 0.99140115 0.59792965] 

0.48987161733149903


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
import numpy as np
z=np.ones((4,4))
z[1:-1, 1:-1]=0
print(z)


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
import numpy as np
z=np.ones((4,4))
z=np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
import numpy as np


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
import numpy as np
z=np.ones((3,3))
print(z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
import numpy as np
z=np.ones((3,3))
z=np.zeros((8,8), dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
import numpy as np

x=np.unravel_index(99,(6,7,8))
print(x)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
import numpy as np
x= np.arange((2))
y=8
z=4
m=(8,4)
print('\n', np.tile(x,m))


 [[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
import numpy as np
x = np.random.random((5,5))
max, min= x.max(), x.min()
x=(x-min)/(max-min)
print(x)

[[0.23347959 0.17461285 0.25365442 0.45752052 0.01909707]
 [0.15821978 1.         0.98188327 0.72538198 0.27490086]
 [0.         0.95299115 0.65162344 0.36967945 0.45800187]
 [0.06193006 0.04198978 0.94956121 0.92392826 0.75230887]
 [0.23990584 0.21860586 0.7137274  0.06112027 0.07128687]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
import numpy as np
x=np.dtype([('R', np.ubyte),
            ('G', np.ubyte),
            ('B', np.ubyte),
            ('A', np.ubyte)])
print(x)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
import numpy as np
x= np.random.random((5,3))
y= np.random.random((3,2))
res=np.dot(x,y)
print(res, '\n')
res1= x@y
print(res1)

[[0.3552181  0.81792448]
 [0.72191258 1.05029364]
 [0.26773617 0.83364067]
 [0.05635186 0.11935576]
 [0.80541837 1.39736774]] 

[[0.3552181  0.81792448]
 [0.72191258 1.05029364]
 [0.26773617 0.83364067]
 [0.05635186 0.11935576]
 [0.80541837 1.39736774]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
import numpy as np
x= np.arange(11)
x[(3<x) & (x<8)]*= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
import numpy as np
x=np.sum(range(5),-1)
print(x)

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
import numpy as np
z=np.arange(10)
print(z**z)
print(2<<z>>2)
print(z<-z)
print(1j*z)
print(z/1/1)
print(z<z>z)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
import numpy as np
x=np.array(0)
y=np.array(0)
z=np.array([np.nan]).astype(int).astype(float)
print(x/y)
print(x//y)
print(z)

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
import numpy as np
x=np.random.random((2,2))
print(x)
a=np.ceil(x)
print(a)
b=np.abs(x)
print(b)

[[0.98610438 0.41704823]
 [0.87084839 0.58380217]]
[[1. 1.]
 [1. 1.]]
[[0.98610438 0.41704823]
 [0.87084839 0.58380217]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
import numpy as np
x=np.arange(10)
y=np.arange(2,8)
print(x, '\n')
print(y, '\n')
z=np.intersect1d(x,y)
print(z,)

[0 1 2 3 4 5 6 7 8 9] 

[2 3 4 5 6 7] 

[2 3 4 5 6 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
import numpy as np
x=np.random.random(100).reshape(5,5,5) * np.nan
np.seterr(all='ignore')
print(x)

ValueError: ignored

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np
x=np.sqrt(-1)
y=np.emath.sqrt(-1)
print(x==y)

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
x=pd.datetime.now()
a=np.array(np.datetime64(x))
y=x-timedelta()
b=np.array(np.datetime64(y))
z=x+timedelta()
c=np.array(np.datetime64(z))
print(a)
print(b)
print(c)

2022-08-10T10:08:34.323247
2022-08-10T10:08:34.323247
2022-08-10T10:08:34.323247


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  after removing the cwd from sys.path.


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
import numpy as np
x=np.arange('2016-07','2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
import numpy as np
A=int(input('Enter the Value:'))
B=int(input('Enter the Value:'))
B=np.add(A,B)
A=np.multiply(A,B)
A=np.negative(A)
A=np.divide(A,2)
z=((A+B)*(-A/2))
print(z)

Enter the Value:10
Enter the Value:12
-4840.0


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
import numpy as np
x=np.random.random(8)
print(np.floor(x))
print(np.ceil(x))
print(x.astype(int))
print(np.trunc(x))
print(x-x%1)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
import numpy as np
x= np.arange(0,5)
y=5
z=1
m=(1,5)
print('\n', np.tile(x,m))


 [[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
import numpy as np
x=np.linspace(0,1,11, endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
import numpy as np
x=np.random.random(10)
print(np.sort(x))

[0.02797859 0.17546013 0.23635843 0.28310047 0.28585181 0.45152362
 0.53945326 0.59318489 0.64870025 0.7009667 ]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
import numpy as np
x=np.arange(10)
print(np.add.reduce(x))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
import numpy as np
x=np.random.random(10)
y=np.random.random(20)

res=np.array_equal(x,y)
print(res)

False



#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
import numpy as np
x=np.ones(10)
x.flags.writeable= False
x[0]=1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
import numpy as np
x=np.random.random((10,2))
print(x, '\n')
y,z=x[:,0],x[:,1]
a=np.sqrt(y**2+z**2)
b=np.arctan2(z,y)
print(a,'\n')
print(b)

[[0.95468591 0.02222651]
 [0.76413699 0.21285062]
 [0.44831037 0.65196135]
 [0.85623061 0.46472774]
 [0.16704154 0.2003782 ]
 [0.54523477 0.50662881]
 [0.75040451 0.42610412]
 [0.32942682 0.8076776 ]
 [0.00489927 0.53741224]
 [0.36110641 0.85515289]] 

[0.95494461 0.79322804 0.79122423 0.97421904 0.26087219 0.74428067
 0.86294359 0.87227583 0.53743457 0.92826952] 

[0.02327729 0.27166393 0.96841844 0.4972677  0.87588223 0.74871219
 0.51643108 1.18352461 1.56168018 1.17123929]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
import numpy as np
x=np.random.random(10)
x[x.argmax()]=0
print(x)

[0.02239654 0.57111423 0.         0.62242542 0.5955595  0.24320196
 0.64519512 0.46257403 0.75945304 0.32531123]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
import numpy as np
from numpy.core.function_base import linspace
x=np.zeros((10,10)),[('y',float),('z',float)]
x['y'],x['z']=np.meshgrid(np.linspace(0,1,5),
                          np.linspace(0,1,5))
print(x)

TypeError: ignored

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
import numpy as np
x=np.arange(10)
z=x+0.5
a=1/np.subtract.outer(x,z)
print(a)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333 -0.11764706 -0.10526316]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615 -0.13333333 -0.11764706]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818 -0.15384615 -0.13333333]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222 -0.18181818 -0.15384615]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429 -0.22222222 -0.18181818]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.         -0.66666667 -0.4       ]
 [ 0.13333333  0.153846

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
import numpy as np
for dtype in [np.int8, np.int32, np.int64,'\n']:
  print(np.iinfo(dtype).max,'\n')
  print(np.iinfo(dtype).max,'\n')
for dtype in [np.float32, np.float64,'\n']:
  print(np.finfo(dtype).max,'\n')
  print(np.finfo(dtype).min,'\n')
  print(np.finfo(dtype).eps,'\n')

127 

127 

2147483647 

2147483647 

9223372036854775807 

9223372036854775807 

18446744073709551615 

18446744073709551615 

3.4028235e+38 

-3.4028235e+38 

1.1920929e-07 

1.7976931348623157e+308 

-1.7976931348623157e+308 

2.220446049250313e-16 



ValueError: ignored

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
import numpy as np
np.set_printoptions(threshold=1)
x=np.ones((10,10))
print(x)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x=np.arange(100)
y=np.random.uniform(0,100)
index=(np.abs(x-y)).argmin()
print(x[index])

16


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
x=np.random.random((100,2))
y,z=np.atleast_2d(x[:,0],x[:,1])
a=np.sqrt((y-y.T)**2 + (z-z.T)**2)
print(a)

[[0.         0.403005   0.4286332  ... 0.48173215 0.73607015 0.59067974]
 [0.403005   0.         0.71002358 ... 0.75222207 0.35645816 0.22585461]
 [0.4286332  0.71002358 0.         ... 0.81363518 0.936102   0.93355626]
 ...
 [0.48173215 0.75222207 0.81363518 ... 0.         1.1071214  0.83269137]
 [0.73607015 0.35645816 0.936102   ... 1.1071214  0.         0.35251341]
 [0.59067974 0.22585461 0.93355626 ... 0.83269137 0.35251341 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
x=np.arange(20, dtype=np.float32)
x=x.astype(np.int32) #copy=False)
print(x)

[ 0  1  2 ... 17 18 19]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
import numpy as np
from io import StringIO
x=StringIO('''1, 2, 3, 4, 5 \n
              6,  ,  , 7, 8 \n
               ,  , 9,10,11 \n''')
y=np.genfromtxt(x, dtype=np.int, delimiter=',')
print(y)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
import numpy as np
x=np.arange(10).reshape(5,2)
for index, value in np.ndenumerate(x):
  print(index, value)
for index in np.ndindex(x.shape):
  print(index,x[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(3, 0) 6
(3, 1) 7
(4, 0) 8
(4, 1) 9
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(3, 0) 6
(3, 1) 7
(4, 0) 8
(4, 1) 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
import numpy as np
x,y=np.meshgrid(np.linspace(-1,1,15), np.linspace(-1,1,15))
b=np.sqrt(x*x+y*y)
sigma, mu= 1,0
a=np.exp(-((b-mu)**2 / (2 * sigma**2)))
print(a)

[[0.36787944 0.42006453 0.46996266 ... 0.46996266 0.42006453 0.36787944]
 [0.42006453 0.47965227 0.53662863 ... 0.53662863 0.47965227 0.42006453]
 [0.46996266 0.53662863 0.60037304 ... 0.60037304 0.53662863 0.46996266]
 ...
 [0.46996266 0.53662863 0.60037304 ... 0.60037304 0.53662863 0.46996266]
 [0.42006453 0.47965227 0.53662863 ... 0.53662863 0.47965227 0.42006453]
 [0.36787944 0.42006453 0.46996266 ... 0.46996266 0.42006453 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
import numpy as np
a=5
b=3
x=np.ones((a,a))
np.put(x, np.random.choice(range(a*a), b, replace=False),6)
print(x)

[[1. 1. 1. 1. 6.]
 [1. 6. 1. 1. 1.]
 [1. 1. 1. 6. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
import numpy as np
x=np.random.random((10,2))
y=x-x.mean(axis=1, keepdims=True)
y=x-x.mean(axis=1).reshape(-1,1)
print(y)

[[-0.24767435  0.24767435]
 [ 0.01734258 -0.01734258]
 [-0.04729309  0.04729309]
 ...
 [-0.01294061  0.01294061]
 [ 0.10018068 -0.10018068]
 [ 0.06359189 -0.06359189]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
import numpy as np
x=np.random.randint(0,10,(4,4))
print(x)

[[0 6 0 6]
 [6 8 3 3]
 [2 9 5 3]
 [6 0 7 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
import numpy as np
x=np.random.randint(0,15,(5,5))
print((~x.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
import numpy as np
x=np.random.uniform(0, 1,15)
a=2.3
y=x.flat[np.abs(x-a).argmin()]
print(y)

0.9168902631020068


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
import numpy as np
x=np.random.random(3).reshape(3,1)
y=np.random.random(3).reshape(1,3)
z= np.nditer([x,y,None])
for a,b,c in z: c[...]=a+b
print(z.operands[2])

[[0.97352551 0.87701504 0.90457565]
 [0.38828736 0.29177689 0.3193375 ]
 [0.6242689  0.52775843 0.55531904]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
import numpy as np
x=np.ones(15)
y=np.random.randint(0,len(x),25)
np.add.at(x,y, 2)
print(x)

[5. 3. 9. ... 5. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
import numpy as np
x=np.arange(15)
y=np.arange(5,20)
z=np.bincount(x,y)
print(z)

[ 5.  6.  7. ... 17. 18. 19.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
import numpy as np
x=np.random.randint(0,15,(4,5,4,5))
sum=x.sum(axis=(-2,-1))
print(sum)

[[105 149 138 170 127]
 [155 118 105 128 132]
 [139 157 125 120 153]
 [137 140 123 129 129]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
import numpy as np
d=np.arange(1,20)


[ 1  2  3 ... 17 18 19]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
import numpy as np
x=np.random.uniform(0,1,(8,8))
y=np.random.uniform(0,1,(8,8))
print(np.diag(np.dot(x,y)))

[1.50860404 1.72282724 2.88195642 ... 1.99875022 3.82946221 1.43677156]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
x=np.array([1,2,3,4,5])
ax=3
x0=np.zeros(len(x)+ (len(x)-1)*(ax))
x0[::ax+1]=x
print(x0)

[1. 0. 0. ... 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
x=np.random.randint((5,5,3))
y=3*np.ones((5,5))
print(x*y[:,:,None])

[[[ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]]

 [[ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]]

 [[ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]]

 [[ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]]

 [[ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]
  [ 3. 12.  6.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
x=np.arange(30).reshape(5,6)
x[[0,1]]==x[[1,0]]
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [81]:
x=np.random.randint(0,100,(10,3))
y=np.roll(x.repeat(2,axis=1),-1, axis=1)
y=y.reshape(len(y)*3,2)
y=np.sort(y, axis=1)
z=y.view(dtype=[('p0',y.dtype),('p1',y.dtype)])
z=np.unique(z)
print(z)

[( 2, 20) ( 2, 42) ( 2, 51) ... (88, 95) (88, 99) (95, 99)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [82]:
x=np.bincount([1,2,3,4,4,4,4,5,5,5,5,5,6])
y=np.repeat(np.arange(len(x)),x)
print(y)

[1 2 3 ... 5 5 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [85]:
x=np.random.randint(0,10,100)
np.logical_not(x, out=x)

x=np.random.uniform(-1.0, 1.0, 100)
np.negative(x, out=x)

array([ 0.54018816,  0.312386  , -0.50844637, ...,  0.03124193,
        0.4665701 ,  0.96372379])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [97]:
x=np.arange(1,15)
y=stride_tricks.as_strided(x, (11,4),(4,4))
print(y)

NameError: ignored

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [92]:
x=np.random.uniform(0,5,(10,10))
y,z,a=np.linalg.svd(x)
b=np.sum(z>1e-100)
print(b)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [96]:
x=np.random.randint(0,10,40)
print(np.bincount(x).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [98]:
from numpy.lib import stride_tricks
x = np.random.randint(0,5,(10,10))
a = 3
b = 1 + (x.shape[0]-3)
c = 1 + (x.shape[1]-3)
d = stride_tricks.as_strided(x, shape=(b, c, a, a), strides=x.strides + x.strides)
print(d)

[[[[3 3 3]
   [0 3 1]
   [3 3 1]]

  [[3 3 0]
   [3 1 0]
   [3 1 1]]

  [[3 0 2]
   [1 0 0]
   [1 1 3]]

  ...

  [[2 4 4]
   [3 2 0]
   [1 2 2]]

  [[4 4 0]
   [2 0 3]
   [2 2 3]]

  [[4 0 2]
   [0 3 4]
   [2 3 3]]]


 [[[0 3 1]
   [3 3 1]
   [4 4 1]]

  [[3 1 0]
   [3 1 1]
   [4 1 3]]

  [[1 0 0]
   [1 1 3]
   [1 3 4]]

  ...

  [[3 2 0]
   [1 2 2]
   [1 1 1]]

  [[2 0 3]
   [2 2 3]
   [1 1 1]]

  [[0 3 4]
   [2 3 3]
   [1 1 3]]]


 [[[3 3 1]
   [4 4 1]
   [0 1 4]]

  [[3 1 1]
   [4 1 3]
   [1 4 0]]

  [[1 1 3]
   [1 3 4]
   [4 0 0]]

  ...

  [[1 2 2]
   [1 1 1]
   [4 0 4]]

  [[2 2 3]
   [1 1 1]
   [0 4 3]]

  [[2 3 3]
   [1 1 3]
   [4 3 0]]]


 ...


 [[[4 4 2]
   [3 4 3]
   [4 1 1]]

  [[4 2 3]
   [4 3 1]
   [1 1 1]]

  [[2 3 3]
   [3 1 0]
   [1 1 0]]

  ...

  [[1 1 1]
   [0 1 1]
   [1 0 4]]

  [[1 1 4]
   [1 1 1]
   [0 4 0]]

  [[1 4 0]
   [1 1 4]
   [4 0 2]]]


 [[[3 4 3]
   [4 1 1]
   [4 4 4]]

  [[4 3 1]
   [1 1 1]
   [4 4 1]]

  [[3 1 0]
   [1 1 0]
   [4 1 4]]

  ...

  [[0

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [99]:
a,b = 20,30
c = np.ones((a,b,b))
d=np.ones((a,b,1))
sum= np.tensordot(c,d, axes=[[0,2],[0,1]])
print(sum)

[[600.]
 [600.]
 [600.]
 ...
 [600.]
 [600.]
 [600.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [102]:
x=np.array([('Hi', 3.5, 4),
            'Everyone', 2.4, 5])
y=np.core.records.fromarrays(x.T, 
                             names='col1, col2, col3',
                             formats= 'S8, f8, i8')
print(y)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


ValueError: ignored

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [105]:
x=np.random.rand(100)
print(np.power(x,3), '\n')
print((x*x*x), '\n')

[0.24683598 0.01364752 0.08897288 ... 0.49081944 0.00889692 0.17006011] 

[0.24683598 0.01364752 0.08897288 ... 0.49081944 0.00889692 0.17006011] 



#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [106]:
x=np.random.randint(0,10,(8,3))
y=np.random.randint(0,10,(2,2))
z=(x[np.newaxis, np.newaxis]==y)
a=np.where(z.any(4,2).all(1))[0]
print(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  This is separate from the ipykernel package so we can avoid doing imports until


AttributeError: ignored

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [108]:
x=np.arange(15, dtype=np.uint8)
print(np.unpackbits(x[:, np.newaxis], axis=1))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 1 1 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [109]:

x = np.random.randint(0,2,(6,3))
y = np.ascontiguousarray(x).view(np.dtype((np.void, x.dtype.itemsize * x.shape[1])))
_, idx = np.unique(y, return_index=True)
ux = x[idx]
print(ux)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [110]:
x = np.random.uniform(0,5,15)
y = np.random.uniform(0,5,15)

np.einsum('i->', x)
np.einsum('i,i->i', x, y)
np.einsum('i,i', x, y)
np.einsum('i,j->ij', x, y)

array([[ 9.86235032, 18.18411493,  8.59833697, ..., 10.16925526,
         3.41473858, 16.42622893],
       [ 3.64650947,  6.72340214,  3.17915265, ...,  3.75998463,
         1.26256685,  6.07344064],
       [ 9.6524122 , 17.79703287,  8.41530568, ...,  9.95278411,
         3.34204964, 16.07656668],
       ...,
       [ 8.21801496, 15.15230383,  7.16474872, ...,  8.47375009,
         2.84540417, 13.68750761],
       [ 7.37185185, 13.59215572,  6.42703455, ...,  7.60125536,
         2.5524288 , 12.27818138],
       [ 1.84610303,  3.40382856,  1.60949626, ...,  1.90355163,
         0.63919442,  3.07477529]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [111]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
a = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == a)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [112]:
X = np.random.randn(1000)
n = 10000
idx = np.random.randint(0, X.size, (n, X.size))
means = X[idx].mean(axis=1)
confident = np.percentile(means, [2.5, 97.5])
print(confident)

[-0.05136609  0.07404806]
