<a href="https://colab.research.google.com/github/basangoudapatil/DW-19-assignment/blob/main/Task_5(ground_cricket_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
ground_cricket_data=({"Chirpspersecond": [20.0, 16.0, 19.8, 18.4, 17.1, 15.5, 14.7,
                                         15.7, 15.4, 16.3, 15.0, 17.2, 16.0, 17.0,
                                         14.4],
                       "Ground_Temperature": [88.6, 71.6, 93.3, 84.3, 80.6, 75.2, 69.7,
                                              71.6, 69.4, 83.3, 79.6, 82.6, 80.6, 83.5,
                                              76.3]})
df=pd.DataFrame(ground_cricket_data)
print(df)

    Chirpspersecond  Ground_Temperature
0              20.0                88.6
1              16.0                71.6
2              19.8                93.3
3              18.4                84.3
4              17.1                80.6
5              15.5                75.2
6              14.7                69.7
7              15.7                71.6
8              15.4                69.4
9              16.3                83.3
10             15.0                79.6
11             17.2                82.6
12             16.0                80.6
13             17.0                83.5
14             14.4                76.3


In [ ]:
df.shape

(15, 2)

In [ ]:
df.columns

Index(['Chirpspersecond', 'Ground_Temperature'], dtype='object')

In [ ]:
df.Chirpspersecond.dtypes

dtype('float64')

**Chirps**/**Second**

In [ ]:
df.Chirpspersecond.values

array([20. , 16. , 19.8, 18.4, 17.1, 15.5, 14.7, 15.7, 15.4, 16.3, 15. ,
       17.2, 16. , 17. , 14.4])

In [ ]:
df.Chirpspersecond.unique()

array([20. , 16. , 19.8, 18.4, 17.1, 15.5, 14.7, 15.7, 15.4, 16.3, 15. ,
       17.2, 17. , 14.4])

In [ ]:
df.Chirpspersecond.isnull().sum()

0

In [ ]:
df.Chirpspersecond.describe()

count    15.000000
mean     16.566667
std       1.712837
min      14.400000
25%      15.450000
50%      16.000000
75%      17.150000
max      20.000000
Name: Chirpspersecond, dtype: float64

**Ground**-**Temperature**

In [ ]:
df.Ground_Temperature.values

array([88.6, 71.6, 93.3, 84.3, 80.6, 75.2, 69.7, 71.6, 69.4, 83.3, 79.6,
       82.6, 80.6, 83.5, 76.3])

In [ ]:
df.Ground_Temperature.unique()

array([88.6, 71.6, 93.3, 84.3, 80.6, 75.2, 69.7, 69.4, 83.3, 79.6, 82.6,
       83.5, 76.3])

In [ ]:
df.Ground_Temperature.isnull().sum()

0

In [ ]:
df.Ground_Temperature.dtypes

dtype('float64')

In [ ]:
df.Ground_Temperature.describe()

count    15.000000
mean     79.346667
std       7.020467
min      69.400000
25%      73.400000
50%      80.600000
75%      83.400000
max      93.300000
Name: Ground_Temperature, dtype: float64

In [ ]:
df=df.drop_duplicates()

In [ ]:
df.Chirpspersecond.shape, df.Ground_Temperature.shape

((15,), (15,))

**Check for** **Outliers**

In [ ]:
Q3 = df.Chirpspersecond.quantile(0.75)
Q1 = df.Chirpspersecond.quantile(0.25)

iqr = Q3 - Q1
upper_threshold = Q3 + (1.5*iqr)
lower_threshold = Q1 - (1.5*iqr)

print(upper_threshold) #Max value is near to upper threshold
print(lower_threshold) #Min value is well within lower threshold

19.699999999999996
12.9


In [ ]:
df.corr()

Chirpspersecond  Ground_Temperature
Chirpspersecond            1.000000            0.832042
Ground_Temperature         0.832042            1.000000

**Preparing** **Data**

In [ ]:
X = df.loc[:, ['Chirpspersecond']].values
y = df.loc[:, 'Ground_Temperature'].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
y_test, y_train

(array([80.6, 79.6, 88.6]),
 array([71.6, 83.3, 93.3, 71.6, 69.7, 82.6, 75.2, 80.6, 84.3, 76.3, 69.4,
        83.5]))

In [ ]:
X_test.shape, X_train.shape

((3, 1), (12, 1))

Modelling

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
print(regressor.intercept_)

10.888809531333933


In [ ]:
print(regressor.coef_)

[4.10498372]


In [ ]:
print(regressor.predict([[18]]))

[84.77851658]


In [ ]:
y_pred = regressor.predict(X_test)
print(y_pred)

[76.56854913 72.4635654  92.98848402]


In [ ]:
df1 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(df1)

   Actual  Predicted
0    80.6  76.568549
1    79.6  72.463565
2    88.6  92.988484


Metrics

In [ ]:
from sklearn import metrics
print('R2 - SCORE:', metrics.r2_score(y_test,y_pred))

R2 - SCORE: -0.776166170478668


In [ ]:
X = df.loc[:, ['Ground_Temperature']].values
y = df.loc[:, 'Chirpspersecond'].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = regressor.predict(X_test)
print(y_pred)

[16.72686996 15.87963837 19.36484105]


In [ ]:
df2=pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(df2)

   Actual  Predicted
0    15.0  16.726870
1    15.5  15.879638
2    19.8  19.364841


In [ ]:
from sklearn import metrics
print('R2 - SCORE:', metrics.r2_score(y_test,y_pred))

R2 - SCORE: 0.7619266307862604
